### ISSUE TITLE
“Open” API misnomer?

### ISSUE THREAD

**Issue by taylorjdawson** [omdbapi/OMDb-API#153]
Just curious, why is it called an “open” movie database when it isn't actually opensource? What does the open stand for?

**Comment by torben-w** [comment]
I guess it's called "open" because there is an API you can access.

If you look at IMDb, you'll see that they don't have an API that everyone can access (if you bring a lot of money, they'll probably provide something). IMDb has just these daily updated zip-files with incomplete data for everyone to access.

**Comment by ohhsodead** [comment]
I believe it was due to being the first "open" api for having movies/shows data accessible without any payment or restrictions. Just looking at their changelog suggests this is the case:
> 11/02/17
- **FREE KEYS!**  The "open" API is finally open again!

**Comment by omdbapi** [comment]
The OMDb API used to have a tight integration with Freebase (https://www.wikidata.org/wiki/Help:FAQ/Freebase) which was an "open data project".
