### ISSUE TITLE
Status Code 401 returned from search

### ISSUE THREAD

**Issue by a-k-o-r-e-d-e** [omdbapi/OMDb-API#219]
Whenever I make the following request, 
http://www.omdbapi.com/?s=batman&apikey=API_KEY

It returns a 401. please help as to what might be the problem

**Comment by a-k-o-r-e-d-e** [comment]
Figured it out 

The request needs either the 't' or 'i' parameter. so I used
'http://www.omdbapi.com/?t=batman&s=batman&apikey=API_KEY'

**Comment by ches** [comment]
I was having the same problem, and finding your issue I realized that introducing `?t` wasn't necessary but switching the order of `s` and `apikey` resolved it for me.

This made me think at first that the Search API is sensitive to order of query params, that `apikey` **must** come first. But after being able to reproduce the ordering difference at first, some time later the reproduction was no longer repeatable…

So I believe what we've seen is a caching behavior bug rather than ordering sensitivity of query params. I had a newly minted API key, probably attempted to make a request with it before I clicked the email verification link for it, so that exact request URL got cached with an error response for a while. Reordering params caused a cache miss which resulted in a successful request.

Just replying to your old issue in case it sheds some light for anyone else finding it in the same situation. But also might be worth filing a new issue for this:

**`?t` and `?i` are supposed to be mutually exclusive, but `?s` should also be mutually exclusive with either `?t` or `?i` since Search and IMDB/Title lookup are different APIs…** OMDb really ought to reject http://www.omdbapi.com/?t=batman&s=batman&apikey=API_KEY as an invalid request, IMO. It could reduce confusion about how to use the API properly, and what's a cache busting issue vs. a quirk that a request format is accepted.

Below was my initial reproduction of simply changing parameter order and getting a different result, but after some time this was no longer repeatable.

```
$ http https://www.omdbapi.com s=="Mickey 17" apikey=="$OMDB_API_KEY"
HTTP/1.1 401 Unauthorized
Age: 3039
CF-Cache-Status: HIT
CF-RAY: 920b9ff5a8777b40-BKK
Cache-Control: public, max-age=86400
Connection: keep-alive
Content-Length: 47
Content-Type: application/json; charset=utf-8
Date: Sat, 15 Mar 2025 11:21:01 GMT
Server: cloudflare
access-control-allow-origin: *
expires: Sat, 15 Mar 2025 11:30:22 GMT
last-modified: Sat, 15 Mar 2025 10:30:22 GMT
vary: *, Accept-Encoding
x-aspnet-version: 4.0.30319
x-powered-by: ASP.NET

{
    "Error": "Invalid API key!",
    "Response": "False"
}

$ http https://www.omdbapi.com apikey=="$OMDB_API_KEY" s=="Mickey 17"
HTTP/1.1 200 OK
Age: 1637
CF-Cache-Status: HIT
CF-RAY: 920b9ec7da397b6c-BKK
Cache-Control: public, max-age=86400
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Sat, 15 Mar 2025 11:20:12 GMT
Server: cloudflare
Transfer-Encoding: chunked
access-control-allow-origin: *
expires: Sat, 15 Mar 2025 11:52:55 GMT
last-modified: Sat, 15 Mar 2025 10:52:55 GMT
vary: *, Accept-Encoding
x-aspnet-version: 4.0.30319
x-powered-by: ASP.NET

{
    "Response": "True",
    "Search": [
        {
            "Poster": "https://m.media-amazon.com/images/M/MV5BZGQwYmEzMzktYzBmMy00NmVmLTkyYTUtOTYyZjliZDNhZGVkXkEyXkFqcGc@._V1_SX300.jpg",
            "Title": "Mickey 17",
            "Type": "movie",
            "Year": "2025",
            "imdbID": "tt12299608"
        }
    ],
    "totalResults": "1"
}
```
